#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: #@ data.values.name + "-db"
  namespace: #@ data.values.namespace
  annotations:
    cnrm.cloud.google.com/project-id: #@ data.values.gcp.projectID
spec:
  region: #@ data.values.gcp.region
  databaseVersion: POSTGRES_9_6
  settings:
    tier: db-custom-1-3840
    #! availabilityType: REGIONAL
    ipConfiguration:
      ipv4Enabled: false
      requireSsl: false
      privateNetworkRef:
        external: default
        #!name: #@ data.values.name + "-db"
  rootPassword:
    value: #@ data.values.name + "-db"
#!    valueFrom:
#!      secretKeyRef:
#!        key: password
#!        name: #@ data.values.name + "-db"
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.name + "-db"
  namespace: #@ data.values.namespace
stringData:
  password: #@ data.values.db.rootPassword
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: example
  namespace: #@ data.values.namespace
  annotations:
    cnrm.cloud.google.com/project-id: #@ data.values.gcp.projectID
spec:
  instanceRef:
    name: #@ data.values.name + "-db"
  password:
    valueFrom:
      secretKeyRef:
        name: #@ data.values.name + "-db"
        key: password